# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mssdk.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmssdk.proto\x12\x05mssdk\"i\n\x0cMssdkRequest\x12\n\n\x02u1\x18\x01 \x01(\r\x12\n\n\x02u2\x18\x02 \x01(\r\x12\n\n\x02u3\x18\x03 \x01(\r\x12\x19\n\x11\x65ncrypted_payload\x18\x04 \x01(\x0c\x12\x1a\n\x12\x63urrent_time_in_ms\x18\x05 \x01(\x12\"Y\n\rMssdkResponse\x12\n\n\x02u1\x18\x01 \x01(\r\x12\n\n\x02u2\x18\x02 \x01(\r\x12\n\n\x02u3\x18\x03 \x01(\r\x12\n\n\x02u4\x18\x04 \x01(\r\x12\n\n\x02u5\x18\x05 \x01(\r\x12\x0c\n\x04\x62ody\x18\x06 \x01(\x0c')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mssdk_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MSSDKREQUEST']._serialized_start=22
  _globals['_MSSDKREQUEST']._serialized_end=127
  _globals['_MSSDKRESPONSE']._serialized_start=129
  _globals['_MSSDKRESPONSE']._serialized_end=218
# @@protoc_insertion_point(module_scope)
